name: Age-Gender Detection CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install opencv-python-headless numpy flask gdown
      shell: bash

    - name: Create models directory
      run: mkdir -p models
      shell: bash

    - name: Download model files from Google Drive
      run: |
        # Download face model and proto
        gdown https://drive.google.com/uc?id=1nKOnInHnPZgfqFvqHBXaGiA_b9AymPXt -O models/face_model.caffemodel
        gdown https://drive.google.com/uc?id=1PbSWggCEdqUEfftAXKFuw-y6dkeL8kAH -O models/face_proto.prototxt
        # Download age model and proto
        gdown https://drive.google.com/uc?id=1FuGyzS4_QWrPNAyiZWT2VOehe99FrkDu -O models/age_model.caffemodel
        gdown https://drive.google.com/uc?id=1cg7GqARX9xn1lp7ivNBDfb0a6EQq81O_ -O models/age_proto.prototxt
        # Download gender model and proto (same as age model)
        gdown https://drive.google.com/uc?id=1cg7GqARX9xn1lp7ivNBDfb0a6EQq81O_ -O models/gender_model.caffemodel
        gdown https://drive.google.com/uc?id=1cg7GqARX9xn1lp7ivNBDfb0a6EQq81O_ -O models/gender_proto.prototxt
      shell: bash

    - name: Run tests
      run: |
        python -m unittest test.py
      shell: bash
